# Generated by Django 5.0.6 on 2024-06-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
